version: '3'

services:
  php:
    image: php:8.1-cli
    volumes:
      - ./src:/var/www/html
    depends_on:
      - curl

#  curl:
#    image: curlimages/curl:latest
#    command: ["tail", "-f", "/dev/null"]