version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alarm-alerter
    tty: true
    environment:
      - ALERTS_IN_UA_TOKEN=
      - TELEGRAM_BOT_TOKEN=
